<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1628658679227" stop="1628658679352">
  <name>scripts.test_aaaa</name>
  <labels/>
  <test-cases>
    <test-case start="1628658679227" status="passed" stop="1628658679243">
      <name>Test_DengLu.test_name_password</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7328-MainThread"/>
        <label name="host" value="DESKTOP-I22UMTN"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1628658679243" status="failed" stop="1628658679352">
      <name>Test_DengLu.test_name_password2</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_aaaa.Test_DengLu object at 0x03AB10B0&gt;

    def test_name_password2(self):
    
&gt;       assert 0
E       assert 0

scripts\test_aaaa.py:16: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="7328-MainThread"/>
        <label name="host" value="DESKTOP-I22UMTN"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
